### ISSUE TITLE
configure_from_yaml / hash seems broken

### ISSUE THREAD

**Issue by benmoss** [markbates/configatron#17]
In a new Rails 3 project

```
>> configatron.configure_from_yaml("#{Rails.root}/config/s3.yml")


NoMethodError: You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.flatten
    from /Users/benjaminmoss/.rvm/gems/ruby-1.9.2-p180@rails31/gems/configatron-2.8.1/lib/configatron/store.rb:306:in `block in parse_options'
    from /Users/benjaminmoss/.rvm/gems/ruby-1.9.2-p180@rails31/gems/configatron-2.8.1/lib/configatron/store.rb:303:in `each'
    from /Users/benjaminmoss/.rvm/gems/ruby-1.9.2-p180@rails31/gems/configatron-2.8.1/lib/configatron/store.rb:303:in `parse_options'
    from /Users/benjaminmoss/.rvm/gems/ruby-1.9.2-p180@rails31/gems/configatron-2.8.1/lib/configatron/store.rb:94:in `configure_from_hash'
    from /Users/benjaminmoss/.rvm/gems/ruby-1.9.2-p180@rails31/gems/configatron-2.8.1/lib/configatron/store.rb:105:in `configure_from_yaml'
    from /Users/benjaminmoss/.rvm/gems/ruby-1.9.2-p180@rails31/gems/configatron-2.8.1/lib/configatron/configatron.rb:15:in `method_missing'
    from (irb):35
    from /Users/benjaminmoss/.rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0.rc4/lib/rails/commands/console.rb:45:in `start'
    from /Users/benjaminmoss/.rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0.rc4/lib/rails/commands/console.rb:8:in `start'
    from /Users/benjaminmoss/.rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0.rc4/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

The yml: 

```
default: &default
  access_key_id: access_key
  secret_access_key: secret_access_key

development:
  bucket: develop
  <<: *default

production:
  bucket: production
  <<: *default

test: &test
```
